#
# Copyright © 2021 NeuroByte Tech. All rights reserved.
#
# NeuroByte Tech is the Developer Company of Rohan Mathew.
#
# Project: latinvocab
# File Name: system.properties
# Last Modified: 07/05/2021, 20:28
#
java.runtime.version=15