#
# Copyright © 2021 NeuroByte Tech. All rights reserved.
#
# NeuroByte Tech is the Developer Company of Rohan Mathew.
#
# Project: latinvocab
# File Name: application.properties
# Last Modified: 29/03/2021, 16:15
#

server.port=${PORT:6789}
# Ensure application is run in Vaadin 14/npm mode
vaadin.compatibilityMode = false
logging.level.org.atmosphere = warn

# To improve the performance during development. 
# For more information https://vaadin.com/docs/v14/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
